### ISSUE TITLE
Error while downloading the document file to be converted - Onlyoffice with Nextxloud

### ISSUE THREAD

**Issue by jcaplu** [ONLYOFFICE/docker-onlyoffice-owncloud#37]
Hi Everyone

I installed Onlyoffice with docker on a Linux 4.19.0-6-amd64 system running with Apache2 with a Nextcloud installed on it.

All the SSL-certifiactes are made and valid. The vhosts file are correct as well. The document server is running and seems to be good! So far all good :-) 

I installed the docker with the following command:
`docker run -i -t -d -p 127.0.0.1:9981:80 -e JWT_ENABLED='true' -e JWT_SECRET='mysecretkey' -e JWT_HEADER="Authorization" --restart=always --name CAP-Office onlyoffice/documentserver`

In the default.json file I changed `rejectUnauthorized` to `false`

In the Nextcloud config.php file i added:
` 'onlyoffice' =>
  array (
    'verify_peer_off' => true,
    'jwt_header' => 'Authorization',
    'jwt_secret' => 'mysecretkey',
  ),`

But still if I configure the Onlyoffice App on my Nextcloud I get the following error:

> Fehler beim Anschließen (Im Dokumentenservice ist ein Fehler aufgetreten: Error while downloading the document file to be converted.)

which means as much as...

> Error during connection (An error has occurred in the document service: Error while downloading the document file to be converted)

I checked also the log file and there I get the following msg as far I try to save the settings in my nextcloud (/var/log/onlyoffice/documentserver/converter/out.log): 

> [ERROR] nodeJS - error downloadFile:url=https://cloud.DOMAIN.ch/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.j7mrSSx3GdHTMhAFwRCkko9v60vmffHX3EeZ6eee1g4;attempt=1;code:ETIMEDOUT;connect:true;(id=conv_check_876118450_docx)
> Error: ETIMEDOUT
>     at Timeout._onTimeout (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:849:19)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)

If I check the link in the error msg i get the following output on the page:

> {"message":"Access denied"}

Any Inputs/Ideas/Solutions?

Thank you for your help already now!

**Comment by LinneyS** [comment]
Hi @jcaplu 
`https://cloud.DOMAIN.ch/` is accessible from the document server container?

**Comment by jcaplu** [comment]
Hi @LinneyS 
Thank you for helping...
I just tried by pinging first `google.com` (Works), then google IP -> `8.8.8.8 `(Works) and finally my `cloud.DOMAIN.ch` (No response).

So then i made a traceroute:

> traceroute to cloud.DOMAIN.ch (XX.XX.XX.60), 30 hops max, 60 byte packets
 1  172.17.0.1 (172.17.0.1)  0.042 ms  0.016 ms  0.013 ms
 2  centrobusiness (192.168.10.1)  0.619 ms  0.742 ms  0.823 ms
 3  XXX.X.XXX.193 (XXX.X.XXX.193)  4.817 ms  4.894 ms  4.959 ms 
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

(Line 0: X = my fix IP, Line 3: X = Any Public IP)

Do you have any idea why this happens and how I could solve it?

**Comment by CarlOnlyoffice** [comment]
Hello @jcaplu,
Evidently, the document server cannot reach your Nextcloud, that's why the error happens. As a workaround, please try to add the IP address + the domain name of your Nextcloud to /etc/hosts inside the Document Server container. After that try to save the settings in the integration app anew.
