### ISSUE TITLE
Returns 500 301

### ISSUE THREAD

**Issue by Ivan-Igorevich** [ONLYOFFICE/docker-onlyoffice-owncloud#43]
Hello, i installed this repository on my pc with internet connection enabled, almost everything went fine (except it refused to connect to my `pg database`), saved `images` and `app_data`, transferred 'em to a close network server, loaded images, and ported volumes to a server directories (with contents, copied earlier). As i `docker-compose up -d` this repo, it turns up and running, but as i enter the homepage in browser, it returns an `internal server error`. i can see `500 301` in `nginx` log and just `500` in `app_server` log. Can i use some help, solving this one?

**Comment by HelenBelova17** [comment]
Hello @**Ivan-Igorevich**, please specify some more information, as we cannot reproduce the described issue on our side:

1. OS of the server;
2. Version of Owncloud;
3. Did you perform default installation or changed some parameters (ports or something else)?

**Comment by Ivan-Igorevich** [comment]
Of course you cannot, cos you have the Internet connection))) here's my `uname` and compose file. The only thing i changed is that volumes are actual folders, and output ports of `nginx` are changed to `8880` and `2443` respectively. because `80` and `443` are busy on this machine. The rest of the compose file left unchanged.

``` bash
root@node:/home/srv/docker/docker-onlyoffice-nextcloud# uname -a
Linux node 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
root@node:/home/srv/docker/docker-onlyoffice-nextcloud# cat docker-compose.yml
version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '9000'
    ports:
      - 9000:9000
    volumes:
      - ./app_data:/var/www/html
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - ./document_data:/var/www/onlyoffice/Data
      - ./document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 8880:80
      - 2443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app_data:/var/www/html
volumes:
  mysql_data:
root@node:/home/srv/docker/docker-onlyoffice-nextcloud#
```
Folders were ported to host, cos they were ported to host and filled with files on an online machine. My guess is that these files were not enough, and container still wants to get something from the Internet

**Comment by Ivan-Igorevich** [comment]
here's what i found in my logs.. could it be helpful in solving my issue?
```
[2020-03-23T07:27:57.995] [WARN] nodeJS - Express server starting...
[2020-03-23T07:27:58.008] [WARN] nodeJS - { Error: ENOENT: no such file or directory, open '/var/www/onlyoffice/documentserver/../Data/license.lic'
    at Object.openSync (fs.js:443:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:490:32)
    at Object.readFileSync (fs.js:343:35)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:686:36)
    at Object.exports.readLicense (/snapshot/server/build/server/Common/sources/license.js:0:0)
    at exports.readLicense.next (<anonymous>)
    at readLicense (/snapshot/server/build/server/DocService/sources/server.js:0:0)
    at readLicense.next (<anonymous>)
    at /snapshot/server/build/server/DocService/sources/server.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/DocService/node_modules/co/index.js:65:19)
    at /snapshot/server/build/server/DocService/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/snapshot/server/build/server/DocService/node_modules/co/index.js:50:10)
    at updateLicense (/snapshot/server/build/server/DocService/sources/server.js:0:0)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/server.js:0:0)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/www/onlyoffice/documentserver/../Data/license.lic' }
[2020-03-23T07:27:58.015] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
```
